const assert=require('node:assert/strict');
const {matchMeetingRooms}=require('./matchMeetingRooms');
const room=(id,seats,location='u')=>({_id:id,name:id,company:'c',seats,location,isActive:true});
const rooms=[room('small',2),room('boardroom',8),room('suite',10,'v')];
const generated=room('generated',6);
const meeting=(id,bookedRoom,start,end)=>({_id:id,company:'c',bookedRoom,startTime:new Date(`2026-06-01T${start}:00Z`),endTime:new Date(`2026-06-01T${end}:00Z`),status:'Completed'});
const input={rooms,allRooms:[generated,...rooms],generatedRooms:new Set(['generated']),units:[{_id:'u',unitNo:'Office A'},{_id:'v',unitNo:'Office B'}],existing:[meeting('existing','boardroom','09:00','10:00'),meeting('first','generated','09:00','10:00'),meeting('second','generated','09:30','10:30'),meeting('third','generated','10:00','11:00')]};
const result=matchMeetingRooms(input);
assert.equal(result.changes[0].bookedRoom,'suite');
assert.equal(result.changes[1].bookedRoom,'boardroom');
assert.equal(result.unmatched.length,1);
assert.equal(result.unmatched[0].meeting,'second');
assert.equal(input.existing[1].bookedRoom,'generated');
assert(!result.changes.some(c=>c.bookedRoom==='small'));
const rerun=matchMeetingRooms({...input,existing:result.meetings});
assert.equal(rerun.changes.length,0);
const extended=matchMeetingRooms({...input,existing:[{...input.existing[0],extendTime:new Date('2026-06-01T11:00:00Z')},input.existing[3]]});
assert.equal(extended.changes[0].bookedRoom,'suite');
console.log('Passed: seat capacity, same-unit preference, overlapping and extended bookings, adjacent slots, unmatched reporting, and reruns.');
